<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class MovieSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('movies')->truncate();

        $movies = [
            [
                'title' => 'Inception',
                'slug' => 'inception',
                'description' => 'A thief who steals corporate secrets through dream-sharing technology.',
                'director' => 'Christopher Nolan',
                'writers' => 'Christopher Nolan',
                'stars' => 'Leonardo DiCaprio, Joseph Gordon-Levitt',
                'poster' => 'https://image.tmdb.org/t/p/w500/8IB2e4r4oVhHnANbnm7O3Tj6tF8.jpg',
                'release_date' => '2010-07-16',
                'duration' => 148,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Interstellar',
                'slug' => 'interstellar',
                'description' => 'A team travels through a wormhole in space to ensure humanity\'s survival.',
                'director' => 'Christopher Nolan',
                'writers' => 'Jonathan Nolan, Christopher Nolan',
                'stars' => 'Matthew McConaughey, Anne Hathaway',
                'poster' => 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
                'release_date' => '2014-11-07',
                'duration' => 169,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Avengers: Endgame',
                'slug' => 'avengers-endgame',
                'description' => 'The Avengers assemble once more to reverse Thanos\' actions.',
                'director' => 'Anthony Russo, Joe Russo',
                'writers' => 'Christopher Markus, Stephen McFeely',
                'stars' => 'Robert Downey Jr., Chris Evans',
                'poster' => 'https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
                'release_date' => '2019-04-26',
                'duration' => 181,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Parasite',
                'slug' => 'parasite',
                'description' => 'A poor family schemes to become employed by a wealthy household.',
                'director' => 'Bong Joon-ho',
                'writers' => 'Bong Joon-ho',
                'stars' => 'Song Kang-ho, Lee Sun-kyun',
                'poster' => 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
                'release_date' => '2019-05-30',
                'duration' => 132,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Joker',
                'slug' => 'joker',
                'description' => 'A mentally troubled comedian embarks on a downward spiral.',
                'director' => 'Todd Phillips',
                'writers' => 'Todd Phillips, Scott Silver',
                'stars' => 'Joaquin Phoenix',
                'poster' => 'https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
                'release_date' => '2019-10-04',
                'duration' => 122,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Fight Club',
                'slug' => 'fight-club',
                'description' => 'An insomniac office worker forms an underground fight club.',
                'director' => 'David Fincher',
                'writers' => 'Jim Uhls',
                'stars' => 'Brad Pitt, Edward Norton',
                'poster' => 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
                'release_date' => '1999-10-15',
                'duration' => 139,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Forrest Gump',
                'slug' => 'forrest-gump',
                'description' => 'The presidencies of Kennedy and Johnson through the eyes of Forrest Gump.',
                'director' => 'Robert Zemeckis',
                'writers' => 'Eric Roth',
                'stars' => 'Tom Hanks',
                'poster' => 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
                'release_date' => '1994-07-06',
                'duration' => 142,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'The Matrix',
                'slug' => 'the-matrix',
                'description' => 'A hacker discovers reality is a simulation.',
                'director' => 'Lana Wachowski, Lilly Wachowski',
                'writers' => 'The Wachowskis',
                'stars' => 'Keanu Reeves',
                'poster' => 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
                'release_date' => '1999-03-31',
                'duration' => 136,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Titanic',
                'slug' => 'titanic',
                'description' => 'A seventeen-year-old aristocrat falls in love with a kind but poor artist.',
                'director' => 'James Cameron',
                'writers' => 'James Cameron',
                'stars' => 'Leonardo DiCaprio, Kate Winslet',
                'poster' => 'https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg',
                'release_date' => '1997-12-19',
                'duration' => 194,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Gladiator',
                'slug' => 'gladiator',
                'description' => 'A former Roman General sets out to exact vengeance.',
                'director' => 'Ridley Scott',
                'writers' => 'David Franzoni',
                'stars' => 'Russell Crowe',
                'poster' => 'https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg',
                'release_date' => '2000-05-05',
                'duration' => 155,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Whiplash',
                'slug' => 'whiplash',
                'description' => 'A promising drummer enrolls at a cut-throat music conservatory.',
                'director' => 'Damien Chazelle',
                'writers' => 'Damien Chazelle',
                'stars' => 'Miles Teller, J.K. Simmons',
                'poster' => 'https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg',
                'release_date' => '2014-10-10',
                'duration' => 106,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Dark Knight',
                'slug' => 'the-dark-knight',
                'description' => 'Batman faces the Joker, a criminal mastermind spreading chaos in Gotham.',
                'director' => 'Christopher Nolan',
                'writers' => 'Jonathan Nolan, Christopher Nolan',
                'stars' => 'Christian Bale, Heath Ledger',
                'poster' => 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
                'release_date' => '2008-07-18',
                'duration' => 152,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'The Shawshank Redemption',
                'slug' => 'the-shawshank-redemption',
                'description' => 'Two imprisoned men bond over years, finding solace and redemption.',
                'director' => 'Frank Darabont',
                'writers' => 'Frank Darabont',
                'stars' => 'Tim Robbins, Morgan Freeman',
                'poster' => 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
                'release_date' => '1994-09-23',
                'duration' => 142,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'The Lord of the Rings: The Return of the King',
                'slug' => 'lotr-return-of-the-king',
                'description' => 'Gandalf and Aragorn lead the World of Men against Sauron.',
                'director' => 'Peter Jackson',
                'writers' => 'Fran Walsh, Philippa Boyens',
                'stars' => 'Elijah Wood, Viggo Mortensen',
                'poster' => 'https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
                'release_date' => '2003-12-17',
                'duration' => 201,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Pulp Fiction',
                'slug' => 'pulp-fiction',
                'description' => 'The lives of two mob hitmen intertwine in four tales of violence.',
                'director' => 'Quentin Tarantino',
                'writers' => 'Quentin Tarantino',
                'stars' => 'John Travolta, Samuel L. Jackson',
                'poster' => 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
                'release_date' => '1994-10-14',
                'duration' => 154,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Dune',
                'slug' => 'dune',
                'description' => 'Paul Atreides leads nomadic tribes in a battle to control the desert planet.',
                'director' => 'Denis Villeneuve',
                'writers' => 'Jon Spaihts, Denis Villeneuve',
                'stars' => 'Timothée Chalamet, Zendaya',
                'poster' => 'https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg',
                'release_date' => '2021-10-22',
                'duration' => 155,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Oppenheimer',
                'slug' => 'oppenheimer',
                'description' => 'The story of J. Robert Oppenheimer and the creation of the atomic bomb.',
                'director' => 'Christopher Nolan',
                'writers' => 'Christopher Nolan',
                'stars' => 'Cillian Murphy, Emily Blunt',
                'poster' => 'https://image.tmdb.org/t/p/w500/ptpr0kGAckfQkJeJIt8st5dglvd.jpg',
                'release_date' => '2023-07-21',
                'duration' => 180,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Spider-Man: No Way Home',
                'slug' => 'spider-man-no-way-home',
                'description' => 'Spider-Man seeks help from Doctor Strange after his identity is revealed.',
                'director' => 'Jon Watts',
                'writers' => 'Chris McKenna, Erik Sommers',
                'stars' => 'Tom Holland, Zendaya',
                'poster' => 'https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
                'release_date' => '2021-12-17',
                'duration' => 148,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'The Batman',
                'slug' => 'the-batman',
                'description' => 'Batman uncovers corruption in Gotham while pursuing the Riddler.',
                'director' => 'Matt Reeves',
                'writers' => 'Matt Reeves, Peter Craig',
                'stars' => 'Robert Pattinson, Zoë Kravitz',
                'poster' => 'https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg',
                'release_date' => '2022-03-04',
                'duration' => 176,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'John Wick',
                'slug' => 'john-wick',
                'description' => 'An ex-hitman comes out of retirement to track down gangsters.',
                'director' => 'Chad Stahelski',
                'writers' => 'Derek Kolstad',
                'stars' => 'Keanu Reeves',
                'poster' => 'https://image.tmdb.org/t/p/w500/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg',
                'release_date' => '2014-10-24',
                'duration' => 101,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Top Gun: Maverick',
                'slug' => 'top-gun-maverick',
                'description' => 'After thirty years, Maverick trains a new generation of pilots.',
                'director' => 'Joseph Kosinski',
                'writers' => 'Ehren Kruger',
                'stars' => 'Tom Cruise, Miles Teller',
                'poster' => 'https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
                'release_date' => '2022-05-27',
                'duration' => 131,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Everything Everywhere All at Once',
                'slug' => 'everything-everywhere-all-at-once',
                'description' => 'A woman discovers she must connect with parallel universe versions of herself.',
                'director' => 'Daniel Kwan, Daniel Scheinert',
                'writers' => 'Daniel Kwan, Daniel Scheinert',
                'stars' => 'Michelle Yeoh, Ke Huy Quan',
                'poster' => 'https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg',
                'release_date' => '2022-03-25',
                'duration' => 139,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Mad Max: Fury Road',
                'slug' => 'mad-max-fury-road',
                'description' => 'In a post-apocalyptic wasteland, Max teams up with Furiosa to escape a tyrant.',
                'director' => 'George Miller',
                'writers' => 'George Miller, Brendan McCarthy',
                'stars' => 'Tom Hardy, Charlize Theron',
                'poster' => 'https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg',
                'release_date' => '2015-05-15',
                'duration' => 120,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'The Prestige',
                'slug' => 'the-prestige',
                'description' => 'Two rival magicians engage in a battle to create the ultimate illusion.',
                'director' => 'Christopher Nolan',
                'writers' => 'Jonathan Nolan, Christopher Nolan',
                'stars' => 'Hugh Jackman, Christian Bale',
                'poster' => 'https://image.tmdb.org/t/p/w500/bdN3gXuIZYaJP7ftKK2sU0nPtEA.jpg',
                'release_date' => '2006-10-20',
                'duration' => 130,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'La La Land',
                'slug' => 'la-la-land',
                'description' => 'A jazz musician and an aspiring actress fall in love while pursuing their dreams.',
                'director' => 'Damien Chazelle',
                'writers' => 'Damien Chazelle',
                'stars' => 'Ryan Gosling, Emma Stone',
                'poster' => 'https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg',
                'release_date' => '2016-12-09',
                'duration' => 128,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'The Wolf of Wall Street',
                'slug' => 'the-wolf-of-wall-street',
                'description' => 'The rise and fall of stockbroker Jordan Belfort.',
                'director' => 'Martin Scorsese',
                'writers' => 'Terence Winter',
                'stars' => 'Leonardo DiCaprio, Jonah Hill',
                'poster' => 'https://image.tmdb.org/t/p/w500/sOxr33wnRuKazR9ClHek73T8qnK.jpg',
                'release_date' => '2013-12-25',
                'duration' => 180,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'The Social Network',
                'slug' => 'the-social-network',
                'description' => 'The story of the founding of Facebook and the lawsuits that followed.',
                'director' => 'David Fincher',
                'writers' => 'Aaron Sorkin',
                'stars' => 'Jesse Eisenberg, Andrew Garfield',
                'poster' => 'https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg',
                'release_date' => '2010-10-01',
                'duration' => 120,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Doctor Strange',
                'slug' => 'doctor-strange',
                'description' => 'A brilliant surgeon discovers the world of mystic arts.',
                'director' => 'Scott Derrickson',
                'writers' => 'Jon Spaihts, Scott Derrickson',
                'stars' => 'Benedict Cumberbatch, Rachel McAdams',
                'poster' => 'https://image.tmdb.org/t/p/w500/uGBVj3bEbCoZbDjjl9wTxcygko1.jpg',
                'release_date' => '2016-11-04',
                'duration' => 115,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Blade Runner 2049',
                'slug' => 'blade-runner-2049',
                'description' => 'A young blade runner discovers a secret that could plunge society into chaos.',
                'director' => 'Denis Villeneuve',
                'writers' => 'Hampton Fancher, Michael Green',
                'stars' => 'Ryan Gosling, Harrison Ford',
                'poster' => 'https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
                'release_date' => '2017-10-06',
                'duration' => 164,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Shutter Island',
                'slug' => 'shutter-island',
                'description' => 'A U.S. Marshal investigates the disappearance of a patient from a psychiatric hospital.',
                'director' => 'Martin Scorsese',
                'writers' => 'Laeta Kalogridis',
                'stars' => 'Leonardo DiCaprio, Mark Ruffalo',
                'poster' => 'https://image.tmdb.org/t/p/w500/kve20tXwUZpu4GUX8l6X7Z4jmL6.jpg',
                'release_date' => '2010-02-19',
                'duration' => 138,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Deadpool',
                'slug' => 'deadpool',
                'description' => 'A wisecracking mercenary gains superpowers after an experiment.',
                'director' => 'Tim Miller',
                'writers' => 'Rhett Reese, Paul Wernick',
                'stars' => 'Ryan Reynolds',
                'poster' => 'https://image.tmdb.org/t/p/w500/fSRb7vyIP8rQpL0I47P3qUsEKX3.jpg',
                'release_date' => '2016-02-12',
                'duration' => 108,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Your Name',
                'slug' => 'your-name',
                'description' => 'Two teenagers mysteriously swap bodies and form a unique connection.',
                'director' => 'Makoto Shinkai',
                'writers' => 'Makoto Shinkai',
                'stars' => 'Ryunosuke Kamiki, Mone Kamishiraishi',
                'poster' => 'https://image.tmdb.org/t/p/w500/q719jXXEzOoYaps6babgKnONONX.jpg',
                'release_date' => '2016-08-26',
                'duration' => 106,
                'url_720' => 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
                'url_1080' => 'https://www.sample-videos.com/video/mp4/1080/big_buck_bunny_1080p_20mb.mp4',
                'url_4k' => 'https://www.sample-videos.com/video/mp4/4k/big_buck_bunny_4k_20mb.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('movies')->insert($movies);

        Schema::enableForeignKeyConstraints();
    }
}
